
model_name_or_path: starcoder2-7b
quantization_bit: 4
quantization_method: bitsandbytes  

stage: sft
do_train: true
finetuning_type: lora
lora_target: all

lora_rank: 16

dataset: perf_train_with_category
template: default
cutoff_len: 22000
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16


output_dir: saves/starcoder7/qlora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true


per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000



